on load:
  delete {quest::*} 
  wait 10 tick

#!  chance of 15%:
#!    set {quest::menge} to <number>
#!    set {quest::item} to <item>
#!    set {quest::info} to <info>
#!    set {quest::belohnung} to <item>
#!    stop



  chance of 15%:
    set {quest::menge} to 1000
    set {quest::item} to damage 
    set {quest::info} to damage
    set {quest::belohnung} to Trident
    stop


  chance of 35%:
    set {quest::menge} to 128
    set {quest::item} to short grass
    set {quest::info} to Grass
    set {quest::belohnung} to 32 Steak
    stop


  chance of 10%:
    set {quest::menge} to 25
    set {quest::item} to diamond ore 
    set {quest::info} to diamond
    set {quest::belohnung} to villager spawn egg
    stop


  chance of 40%:
    set {quest::menge} to 128
    set {quest::item} to dirt 
    set {quest::info} to dirt
    set {quest::belohnung} to 15 iron ore
    stop


  wait 1 tick
  chance of 100%:
    set {quest::menge} to 192
    set {quest::item} to stone 
    set {quest::info} to Stone
    set {quest::belohnung} to 15 iron ore
    stop


  wait 1 tick
  chance of 100%:
    set {quest::menge} to 64
    set {quest::item} to any log
    set {quest::info} to "Wood log"
    set {quest::belohnung} to "20 wood logs"
    stop



on join:
  if {quest::%player%} is not set:
    set {quest::%player%} to 0
  stop




every 25 ticks:
  loop all players:
    quest(loop-player)
    if {quest::%loop-player%} is not set:
      set {quest::%loop-player%} to 0 
       
function quest(p: player):
  wipe {_p}'s sidebar
  set name of sidebar of {_p} to "&7Quest"

  
  set score "§6%{quest::info}% [%{quest::%{_p}%}%|%{quest::menge}%]" in sidebar of {_p} to 2
  set score "&6Belohnung: &6%{quest::belohnung}%" in sidebar of {_p} to 1
 


#on drop:
  #broadcast "%event-item%"



on damage:
  #broadcast "%{quest::fertig::%attacker%}%"
  if {quest::item} is instant damage:
    add damage to {quest::%attacker%}
    if {quest::%attacker%} > {quest::menge}:
      if {quest::fertig::%attacker%} is not set:
        set {quest::fertig::%attacker%} to true
        #broadcast "%{quest::belohnung}%"
        wait 10 ticks
        add {quest::belohnung} to attacker's inventory
      stop


on block break:
  #broadcast "%event-block%"
  if event-block is {quest::item}:
    add 1 to {quest::%player%}
    if {quest::%player%} > {quest::menge}:
      if {quest::fertig::%player%} is not set:
        set {quest::fertig::%player%} to true
        #broadcast "%{quest::belohnung}%"
        wait 10 ticks
        add {quest::belohnung} to player's inventory
      stop